### ISSUE TITLE
Bug Fix (?) on runReadOnBackground for Windows

### ISSUE THREAD

**Issue by lorenberg** [nyholku/purejavahidapi#12] opened 2015-05-08 12:16 UTC
Hello,

first of all I want to congratulate with you for the great work you did! The library is extremely useful and works totally fine (I was having some problems with the other JavaHDI libraries).

Secondly, I wanted to signal you a couple of things on the library.

First of all, the compiled jar you included in /bin/ folder is containing an old version of the HidDevice.java file for windows, I think it is the buggy ones you changed a few weeks ago.
I noticed it because with the jar my class was not working (I was receiving the onInputReport event only every now and then), while when I compiled the library myself it was working quite fine.

Then, I am not sure it is a general problem, but in my case I was using your library to control a custom HID wireless transmitter which is communicating with an external device sending two commands: getInformation and doAction.
The doAction is not supposed to signal an onReport event, but in my case after the first call to getInformation I was always receiving an onReport event containing the same information as the initial call.
To fix this, I just added an m_InputReportMemory.clear() after the onInputReport call in HidDevice,java

As I told you, I am not sure this is true for everyone, but I thought it was interesting for you to be aware of this.

Again, thank you for the great job, and I will keep you informed of possible news.

Best,

Lorenzo

**Comment by nyholku** [comment] 2016-05-22 04:48
Thanks for the feedback. Would be interesting to learn more about receiving a 'ghost' report, it should of course not happen and more over a 'clear' should not cure the problem! 

As this has been sometime I'm closing this but feel free to re-open if you want to work with in finding the root cause.

**Closed** 2016-05-22 08:35 UTC
