### ISSUE TITLE
Not able to read DataLogic Scanner, Device is null with Windows 7 and Windows 8.1

### ISSUE THREAD

**Issue by AvinashKalpavruksha** [nyholku/purejavahidapi#15] opened 2015-06-26 13:58 UTC
Dear friends, I need your immediate help.

My Scenario : I am using DataLogic Barcode SCanner to read QR Diagram using Pure JavaHIDAPI.I am able to read the Other USB Devices like USB HeadPhone.

But while trying to read the DataLogic Scanner,the Device comes NULL.
I Changed the Source Code also .

int share_mode =  (enumerate) ? FILE_SHARE_READ | FILE_SHARE_WRITE : FILE_SHARE_READ | FILE_SHARE_WRITE;

But it Reads other USB Devices and not the Scanner.

Please help for the same how can i read the Data Login Scanner.

Let me know if something more on the requirement is required.

regds
Avinash

**Comment by nyholku** [comment] 2015-06-27 04:29
I suspect some other software is using the device. Try to find out which. Also you could try to use the 

https://github.com/signal11/hidapi

to eliminate a the possibility of a Java/PureJavaHidApi bug.

**Comment by AlexBGar** [comment] 2015-06-29 08:45
Are you sure that the device is an HID device? You can use the Control Panel to find your device and its Vendor and Product codes

**Comment by AvinashKalpavruksha** [comment] 2015-06-29 12:51
Hi, the DataLogic Barcode Scanner device works as a Hid device as well as a Hid Keyboard device.

**Comment by nyholku** [comment] 2015-06-29 12:56
I recommend single stepping into the PureJavaHidApi call and seeing what happens. It is pretty straightforward, direct Windows API calls and if those 'fail' to open the device then there is very little help I can offer. Like I suggested trying with the HIDAPI (which is pretty similar but C) would give you a second opinion about the root cause. I do not know if Windows 7/8 support opening one HID interface from one application while (presumably) the system is keeping the other (keyboard) interface open. Do you have access to an application that works and uses the non-keyboard interface?

**Comment by AvinashKalpavruksha** [comment] 2015-06-29 13:05
Hi, Thanks for your prompt reply. Yes, i have access to an application that works. I can open my USB headphone and for it the device does not come null. I selected PureJavaHidApi because the driver is installed automatically . For JavaHidApi also , i get the scanner device as null but the USB headphone does not come null.

**Comment by AvinashKalpavruksha** [comment] 2015-06-29 13:28
Hi, i am able to list the Scanner device and get its PID and VID perfectly using PureJavaHidApi. Only ,the device  does not open while trying to read the device. HIDAPI is in C. I wanted the solution in java. Here, the JavaHidApi also fails to open the scanner even after applying the patches.

**Comment by nyholku** [comment] 2016-03-19 11:21
Not heard from this since, so I'm closing this, please feel free to re-open if necessary.

**Closed by nyholku** 2016-03-19 11:21 UTC
